---
title: "Join us?"
---

We are often looking for prospective graduate students, post-docs, and undergraduates.

If you are potentially interested in joining our team, please **send Jess an email including the following information**:

- a short CV
- a short paragraph on why you are interested in our group
- (for prospective grad students) what degree and program you’re interested in

**Prospective graduate students:** <br>
Both Horticulture and Crop Science, and Food Science and Technology are direct admit programs (i.e., no rotations), so students will only be admitted once they have found a faculty adviser to support them (both financially and with mentorship) during their degree. For this reason, it’s important to reach out before the application process!

Students interested to start in the Summer or Fall should have completed applications by Nov 30 of the previous year. Most discussions with prospective students occur in Summer/early Fall.

If you have any questions about the application process, please reach out to Jess via email.